version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - app-network

  backend:
    env_file: .env
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "flask --app app.server run --host 0.0.0.0 --port 5000"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - app-network

networks:
   app-network:
     driver: bridge