version: "3"

services:
  test_db:
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_SERVER=db
    - POSTGRES_DB=test_db