"""Add is_active

Revision ID: 2382738a92d6
Revises: d66390af6709
Create Date: 2023-05-30 17:52:45.289352

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2382738a92d6"
down_revision = "d66390af6709"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM("in_progess", "ended", name="gamestatus"),
            nullable=False,
        )
        batch_op.alter_column(
            "date",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )

    with op.batch_alter_table("usergames", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM("win", "lose", "tie", name="gameresult"),
            nullable=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "idle", "waiting_for_game", "in_game", name="userstate"
            ),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "idle", "waiting_for_game", "in_game", name="userstate"
            ),
            nullable=True,
        )
        batch_op.drop_column("is_active")

    with op.batch_alter_table("usergames", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM("win", "lose", "tie", name="gameresult"),
            nullable=True,
        )

    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM("in_progess", "ended", name="gamestatus"),
            nullable=True,
        )

    # ### end Alembic commands ###
