"""Add start time

Revision ID: 464f1c7e0e82
Revises: 6cf7671a83da
Create Date: 2023-06-02 16:21:34.291231

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "464f1c7e0e82"
down_revision = "6cf7671a83da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "date_started",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("date_ended", sa.DateTime(), nullable=False))
        batch_op.drop_column("date")
        batch_op.drop_column("time_in_seconds")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "time_in_seconds", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "date",
                postgresql.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("date_ended")
        batch_op.drop_column("date_started")

    # ### end Alembic commands ###
