"""Add nullable date ended

Revision ID: bc22ca9d006d
Revises: 464f1c7e0e82
Create Date: 2023-06-02 16:32:53.851073

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bc22ca9d006d"
down_revision = "464f1c7e0e82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.alter_column(
            "date_ended", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.alter_column(
            "date_ended", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    # ### end Alembic commands ###
